name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
          - aarch64-apple-darwin
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest

    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          save-always: true
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Install (Musl Tool)
        if : matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt install -qq -y musl-tools --no-install-recommends
      - name: Install (Xcode CommandLine tools)
        if : matrix.target == 'x86_64-apple-darwin'
        run: xcode-select --install
      - name: Install (Rustup)
        run: rustup target add ${{matrix.target}}
      - name: Build
        run: cargo build --release --target=${{matrix.target}}
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: ${{github.sha}}-${{matrix.target}}-artifacts
          path: target/${{matrix.target}}/release/tssubscript
